spring.application.name=gestion-commerciale
server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.security.user.name=admin
spring.security.user.password=admin123
